apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sigma-rs
  labels:
    app: sigma-rs
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: sigma-rs
      component: engine
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace