apiVersion: v1
kind: ServiceAccount
metadata:
  name: sigma-rs
  labels:
    app: sigma-rs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sigma-rs
  labels:
    app: sigma-rs
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sigma-rs
  labels:
    app: sigma-rs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sigma-rs
subjects:
- kind: ServiceAccount
  name: sigma-rs