apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigma-rs
spec:
  template:
    spec:
      containers:
      - name: sigma-rs
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "8000m"
        env:
        - name: RUST_LOG
          value: "warn,sigma_rs=info"
        - name: OTEL_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.monitoring:4317"
        - name: OTEL_SERVICE_NAME
          value: "sigma-rs-prod"
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 30