[defaults]
exclude-files = ["examples/*", "benches/*", "tests/*"]
timeout = "600s"
all-features = true
workspace = true
engine = "llvm"
follow-exec = true

[report]
out = ["Html", "Xml", "Lcov"]
output-dir = "target/coverage"
