name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Build
        run: cargo build --release --no-default-features
      
      - name: Run tests
        run: cargo test --no-default-features
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/sigma-rs
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}